### ISSUE TITLE
Dataset format

### ISSUE THREAD

**Issue by phonPtan** [oufuzhao/EQBM#1]
How can i train in my dataset?
You can define the source_list, target_list, target_label, pretrain_model parameters in config_train.py

**Comment by T-Annika** [comment]
Hi,

Thank you for your interest in our work.

1. The "source_list" is the path of the txt file to indicate your source dataset, the format is like this:
/XXXXX-Your-Source-Dataset-PathXXXXX/XXXXX1.jpg      {$quality labels} 
/XXXXX-Your-Source-Dataset-PathXXXXX/XXXXX2.jpg      {$quality labels} 
/XXXXX-Your-Source-Dataset-PathXXXXX/XXXXX3.jpg      {$quality labels} 
...

2. The "target_list" is the path of the txt file to indicate your target dataset, the format is like this:
/XXXXX-Your-Target-Dataset-PathXXXXX/{$target_label}/XXXXX1.jpg 
/XXXXX-Your-Target-Dataset-PathXXXXX/{$target_label}/XXXXX2.jpg 
/XXXXX-Your-Target-Dataset-PathXXXXX/{$target_label}/XXXXX3.jpg
...

Please note that the "target_label" need to be included in the data path to filter out data with a specific "target label".

3. The "pretrain_model" is the path of the pre-trained face recognition model with the ".pth" pytorch format.

**Comment by oufuzhao** [comment]
Hi,

Thank you for your interest in our work.

The "source_list" is the path of the txt file to indicate your source dataset, the format is like this:
/XXXXX-Your-Source-Dataset-PathXXXXX/XXXXX1.jpg {$quality labels}
/XXXXX-Your-Source-Dataset-PathXXXXX/XXXXX2.jpg {$quality labels}
/XXXXX-Your-Source-Dataset-PathXXXXX/XXXXX3.jpg {$quality labels}
...

The "target_list" is the path of the txt file to indicate your target dataset, the format is like this:
/XXXXX-Your-Target-Dataset-PathXXXXX/{$target_label}/XXXXX1.jpg
/XXXXX-Your-Target-Dataset-PathXXXXX/{$target_label}/XXXXX2.jpg
/XXXXX-Your-Target-Dataset-PathXXXXX/{$target_label}/XXXXX3.jpg
...

Please note that the "target_label" need to be included in the data path to filter out data with a specific "target label".

The "pretrain_model" is the path of the pre-trained face recognition model with the ".pth" pytorch format.

**Comment by phonPtan** [comment]
Thanh you for rep,
I has try with your guide, and pre-trained from https://github.com/TreB1eN/InsightFace_Pytorch but error   
`====================TRAINING LOG====================
Traceback (most recent call last):
  File "/home/phongnt/face_qc/EQBM/./train.py", line 317, in <module>
    adv_net = train_da(conf, trainloader[0], adv_net, epoch=conf.epoch/2)
  File "/home/phongnt//face_qc/EQBM/./train.py", line 218, in train_da
    source_class_output1, _, rank_classifier_output, source_domain_output1, source_domain_output2 = net(input_data1=img_source1, input_data2=img_source2, alpha=alpha)
ValueError: too many values to unpack (expected 5)`

My data: [source_list.txt](https://github.com/user-attachments/files/17469436/source_list.txt)
[target_list.txt](https://github.com/user-attachments/files/17469438/target_list.txt)

**Comment by oufuzhao** [comment]
Hi @phonPtan,

The error message you provided may occur on Line #218 of train.py. The reason seems to be that the number of results returned by "net" does not match the number of variables on the left. But in the code the "net" should call and return [./model/ model_integration.py, Line #108](https://github.com/oufuzhao/EQBM/blob/25550ee479d6df9490362cdce338b889194f6a85/model/model_integrated.py#L108C17-L108C158), which should return five variables. 

I think you can check if the output conforms to the set 5 return values by executing net(input_data1=img_source1, input_data2=img_source2, alpha=alpha). Meanwhile, you can also check if "input_data1" and "input_data2" are valid, and if Line #98-Line #108 in ./model/model_integrate.py is successfully executed.

**Comment by oufuzhao** [comment]
Hi @phonPtan, also, it's worth noting that I found that the images for the "source_list.txt" and "target_list.txt" you provided seem to be the same. Normally, the two sets should be different, but I'm not sure if this will result in other problems.

**Comment by phonPtan** [comment]
> Hi @phonPtan,
> 
> The error message you provided may occur on Line #218 of train.py. The reason seems to be that the number of results returned by "net" does not match the number of variables on the left. But in the code the "net" should call and return [./model/ model_integration.py, Line #108](https://github.com/oufuzhao/EQBM/blob/25550ee479d6df9490362cdce338b889194f6a85/model/model_integrated.py#L108C17-L108C158), which should return five variables.
> 
> I think you can check if the output conforms to the set 5 return values by executing net(input_data1=img_source1, input_data2=img_source2, alpha=alpha). Meanwhile, you can also check if "input_data1" and "input_data2" are valid, and if Line #98-Line #108 in ./model/model_integrate.py is successfully executed.


i found the problem, because i change default value train=True to train=False when i export to ONNX at this line https://github.com/oufuzhao/EQBM/blob/25550ee479d6df9490362cdce338b889194f6a85/model/model_integrated.py#L77C2-L77C78, now it work.

**Comment by phonPtan** [comment]
> Hi @phonPtan, also, it's worth noting that I found that the images for the "source_list.txt" and "target_list.txt" you provided seem to be the same. Normally, the two sets should be different, but I'm not sure if this will result in other problems.
i still don't understand target_list, is it a good face dataset?

**Comment by phonPtan** [comment]
> Hi @phonPtan, also, it's worth noting that I found that the images for the "source_list.txt" and "target_list.txt" you provided seem to be the same. Normally, the two sets should be different, but I'm not sure if this will result in other problems.

i still don't understand target_list, is it a good face dataset?

**Comment by oufuzhao** [comment]
Hi @phonPtan, 

1. Glad you found the problem; 

2. Since the images you just gave me for source_list.txt and target_list.txt are the same, I'm not sure if that's what you were supposed to try. I give you a normal example here to help you understand better, assuming your source domain dataset is from your [source_list.txt](https://github.com/user-attachments/files/17469436/source_list.txt):

BUPT-CBFace-50/images_gen/m.01wskb2/radial_blurred_34_0.jpg 0.00
BUPT-CBFace-50/images_gen/m.01wskb2/radial_blurred_34_1.jpg 0.20
BUPT-CBFace-50/images_gen/m.01wskb2/radial_blurred_34_2.jpg 0.40
BUPT-CBFace-50/images_gen/m.01wskb2/radial_blurred_34_3.jpg 0.60
...

The images of target_list should be different from the source list, and it should be another domain data. Here, I assume that masked is a face wearing a mask, and the "target_label" is "masked" (note that this is just for taking an example). The target_list.txt should be like:

BUPT-CBFace-50/masked/m.01xxxx1/doesnt_matter_what_the_name0.jpg
BUPT-CBFace-50/masked/m.01xxxx1/doesnt_matter_what_the_name1.jpg
BUPT-CBFace-50/masked/m.01xxxx3/doesnt_matter_what_the_name2.jpg
BUPT-CBFace-50/masked/m.01x????/doesnt_matter_what_the_name3.jpg
...

But if you're really trying to your idea and know that the source list and target list are the same images, please ignore me : )

**Comment by phonPtan** [comment]
Hi @oufuzhao
i will try and feedback

thank you <3

**Comment by oufuzhao** [comment]
Hi @phonPtan, you're welcome, look forward to your feedback! If our work can help you, I would gratefully appreciate it that you could give me a star or cite our work. Thank you so so much 👍

**Comment by phonPtan** [comment]
perfect thank you so much.

**Comment by oufuzhao** [comment]
Excellent.

**Comment by phonPtan** [comment]
Can I make model lighter?

**Comment by oufuzhao** [comment]
Sure, you can customize a lighter weight CNN model

**Comment by oufuzhao** [comment]
I tried to design a tiny model to extract face embedding with input 3x96x96, including several convolutional layers and an MLP containing BN, and the performance did not drop much in the application. Unfortunately, I guess I can't find the specific model code at present. But I think you can try the design yourself if you are interested.

**Comment by phonPtan** [comment]
I will research more.
Dataset format has been clear so I will close topic.

Thank you @oufuzhao

**Comment by oufuzhao** [comment]
You're welcome. Glad I could help you @phonPtan  : )
